### ISSUE TITLE
Example for Fuzzy c-means clustering

### ISSUE THREAD

**Issue by jonaslandsgesell** [scikit-fuzzy/scikit-fuzzy#101]
When running the example for c-means clustering (https://pythonhosted.org/scikit-fuzzy/auto_examples/plot_cmeans.html) the algorithm does not yield the expected result which is shown in the reference: The algorihtm returns a maximum in the FPU for 2 centers (where 3 centers are expected to be found). 
Happened to me (with exactly the presented code and also for different seeds) in version 0.1.9 and also the current version on github.

**Comment by JDWarner** [comment]
Can you save and paste in here (GitHub allows images to be drag and drop uploaded) the result of the second figure? That's the nine-part 3x3 grid of figures showing clustering results.

I suspect that the way I set the random seed may not be consistent across all platforms, and two centers got initialized too close together. This would make the problem related to #94, but I want to see that to be sure.

**Comment by jonaslandsgesell** [comment]
First of all thanks for the cool package and the exciting examples!

Here are the output figures of the example script.
![figure_1](https://cloud.githubusercontent.com/assets/5189693/14656363/6d58f09c-0687-11e6-9386-4cd2e91b8f24.png)

![figure_2](https://cloud.githubusercontent.com/assets/5189693/14656362/6d564342-0687-11e6-9f30-4e0751b6b76f.png)

I am not sure wether this problem is related to seeding, since it seems to be independent of the seed I seed numpy with (on Ubuntu 14.04).

**Comment by JDWarner** [comment]
Thanks, that's helpful. A problem like this was reported previously in #80. Unfortunately, despite heroic efforts there, I still cannot reproduce the problem. We went pretty far troubleshooting to no avail.

There is more than one problem. The clustering seems to be happening oddly as stated, but your Matplotlib is also not operating properly or the colors would be correct. As a result it becomes quite challenging to debug, as more than one thing in different packages aren't behaving.

At least one way to solve this was installing the scientific Python stack using Anaconda or Enthought distributions. That solved #80, and I encourage you to consider doing so. This probably isn't the only anomaly you'll run into, otherwise.

**Comment by jonaslandsgesell** [comment]
When I print the centers (cntr) of the clusters that cmeans() returns, I obtain the following in the loop over the number of centers:


[[        nan  4.98522956]
 [        nan  4.98522956]]
/usr/lib/pymodules/python2.7/matplotlib/lines.py:503: RuntimeWarning: invalid value encountered in greater_equal
  return np.alltrue(x[1:] - x[0:-1] >= 0)
[[        nan  4.98522956]
 [        nan  4.98522956]
 [        nan  4.98522956]]
[[        nan  4.98522956]
 [        nan  4.98522956]
 [        nan  4.98522956]
 [        nan  4.98522956]]
[[        nan  4.98522956]
 [        nan  4.98522956]
 [        nan  4.98522956]
 [        nan  4.98522956]
 [        nan  4.98522956]]
[[        nan  4.98522956]
 [        nan  4.98522956]
 [        nan  4.98522956]
 [        nan  4.98522956]
 [        nan  4.98522956]
 [        nan  4.98522956]]
[[        nan  4.98522956]
 [        nan  4.98522956]
 [        nan  4.98522956]
 [        nan  4.98522956]
 [        nan  4.98522956]
 [        nan  4.98522956]
 [        nan  4.98522956]]
[[        nan  4.98522956]
 [        nan  4.98522956]
 [        nan  4.98522956]
 [        nan  4.98522956]
 [        nan  4.98522956]
 [        nan  4.98522956]
 [        nan  4.98522956]
 [        nan  4.98522956]]
[[        nan  4.98522956]
 [        nan  4.98522956]
 [        nan  4.98522956]
 [        nan  4.98522956]
 [        nan  4.98522956]
 [        nan  4.98522956]
 [        nan  4.98522956]
 [        nan  4.98522956]
 [        nan  4.98522956]]
[[        nan  4.98522956]
 [        nan  4.98522956]
 [        nan  4.98522956]
 [        nan  4.98522956]
 [        nan  4.98522956]
 [        nan  4.98522956]
 [        nan  4.98522956]
 [        nan  4.98522956]
 [        nan  4.98522956]
 [        nan  4.98522956]]

It appears to me that the x value of the center is not calculated correctly (possibly due to a division by zero?).

**Comment by JDWarner** [comment]
Given a properly functioning NumPy, there is no possible way you should ever get a NaN out of this algorithm. There are checks in place for this, which raise the minimum value to the limit of floating point precision prior to division.

Is it possible for you to install Python from a different source, especially one of the curated userland distributions like Canopy or Anaconda? My ability to troubleshoot this is limited due to the fact that I cannot reproduce it or find any possible reason for this behavior. As a result, I strongly suspect this is a problem with some other aspect of your Python installation, not scikit-fuzzy. 

I don't say that lightly, but cannot think of any other reason.

**Comment by JDWarner** [comment]
Even if you were to remove Anaconda or Canopy afterward, it would be invaluable to know if this behavior resolved or persisted.

**Comment by jonaslandsgesell** [comment]
I figured out that np.empty(1) returns in some cases a nan. Which then propagates through the algorihtm.
Initializing xpts and ypts instead with
xpts = np.zeros(1)
ypts = np.zeros(1)

fixes the problem.

**Comment by JDWarner** [comment]
Thank you very much for looking into this, @jonaslandsgesell! It seems strange that `np.empty` can return a nan, but for now we should use the fix you suggest.

Would you like to submit a fix, or shall i?

**Comment by jonaslandsgesell** [comment]
Hey, I exchanged all occurances of np.empty with the safer np.zeros function in this pull request #103 .
Thanks for the cool project.

**Comment by jonaslandsgesell** [comment]
Maybe you can Update the Webpage with the example ( http://pythonhosted.org/scikit-fuzzy/auto_examples/plot_cmeans.html ) so that readers don' t run into this problem by accident.
