### ISSUE TITLE
gbellmf documentation has parameters mixed up

### ISSUE THREAD

**Issue by wemily-amazon** [scikit-fuzzy/scikit-fuzzy#115]
Docstring says that 'b' is the center, but 'c' is the center.

[http://pythonhosted.org/scikit-fuzzy/api/skfuzzy.membership.html#skfuzzy.membership.gbellmf](url)

**Comment by JDWarner** [comment]
Good catch, thanks for the report! I'll get right on that.

**Comment by wemily-amazon** [comment]
Thanks!

I also have gotten strange results, at least in the matplotlib figures, when giving parameters as integers where floats are expected, in this and other mf.  It's not really a bug, just a gotcha.

**Comment by JDWarner** [comment]
@wemily-amazon hmm, that sounds like it might well be a bug. Do you use Python 2.x or 3.x? Many of these functions use division, and if they use the simple `/` operator this behaves differently if the denominator is float or int (truncates the result if int) in Python 2. Under Python 3 everything is true division.

The fix is `from __future__ import division` at the top of files, which harmonizes this behavior under Python 2.
