### ISSUE TITLE
Is it possible to obtain a list with the activated rules?

### ISSUE THREAD

**Issue by Chuseuiti** [scikit-fuzzy/scikit-fuzzy#134]
Once a value wants to be simulated, is there any function in the new API to not only obtain the output value but also a list with the activated rules ?

**Comment by JDWarner** [comment]
To be clear, what you're referring to by 'activated rules' would be rules for which the antecedent logic results in a nonzero output value passed to a consequent term?

**Comment by Chuseuiti** [comment]
Yes and thanks for your quick replay.

Get Outlook for Android<https://aka.ms/ghei36>

**Comment by JDWarner** [comment]
At present there is no such function.  However, I see two ways to add/implement this.

* Activation of rules would be checked and cached like how inputs/outputs are, within the `ControlSystemSimulation` objects
* At time of request, minimal calculations would be done for each Rule in the system to determine if it is active

We really have to choose one of these paths.  I lean toward the second, because I see this being used in an interactive/prototyping way, rather than needed for any significant proportion of system computations.  With the second approach, the run time and memory burden of simulations would be unaffected.  

The first saves runtime when this is requested, as it would be a simple lookup.  However, the burden of additional memory and computational time I think is too much for a useful but relatively seldom-used feature.

If that sounds good to you, I think this can be added expediently.  Open to thoughts/opinions.

**Comment by JDWarner** [comment]
If you have s simulation `simulation`, try the following:

``` python
rule_activity = {}
for rule in simulation.ctrl.rules:
    if rule.aggregate_firing[outputs] <= np.finfo(np.float64).eps:
        rule_activity[rule.label] = False
    else:
        rule_activity[rule.label] = True
        # If desired actual activity levels, comment line above & uncomment below
        # rule_activity[rule.label] = rule.aggregate_firing[simulation]
```

Does that behave as you'd expect?

**Comment by Chuseuiti** [comment]
The second option seems to be the best one, as I can see the use case while prototyping the rules, however once the system is stable there is no more use for that feature. 
Regarding your code, by simulation do you mean:

controller=ctrl.ControlSystem([rules])
simulation=ctrl.ControlSystemSimulation(controller)

and what do you mean by outputs? As if I try to run the code, I get an undefined outputs.

**Comment by JDWarner** [comment]
I meant the latter - a `ControlSystemSimulation`.

`outputs` was a typo, it should have been `simulation` in the above snippet.  Fixed now.  Try it again, see if the dictionary makes sense.

**Comment by JDWarner** [comment]
Closing as I believe this is resolved, see above.

**Comment by sunnychampthukral** [comment]
How to view the activated rules
