### ISSUE TITLE
The last result in Fuzzy Control Systems: The Tipping Problem example

### ISSUE THREAD

**Issue by WilliamOu** [scikit-fuzzy/scikit-fuzzy#155]
In the documents, the last example is Fuzzy Control Systems: The Tipping Problem. I copied all codes and ran them, I get 19.847607362 instead of 20.24%, but the last image I got was the same to the last one on the website.

I checked the last image on the website, I found the result should be less than 20 since the black line is on the left side of 20. I also tried to implement this system in Matlab. The Matlab gave 19.9525.

Anyone know where is the problem and why?

thanks

**Comment by JDWarner** [comment]
Thanks for the reminder, we need to update the hard coded 'answer'.

The original implementation was less numerically accurate in an intermediate step.  Since then, we've added a fully correct algorithm.  The 19.8x answer is truly correct, and validated by hand and against multiple other open source fuzzy logic packages.

MATLAB is close, probably close enough, but not quite there.

**Comment by WilliamOu** [comment]
That is a piece of good news. Thanks.

**Comment by JDWarner** [comment]
Closed by 51f9f4d in #162.
