### ISSUE TITLE
Get membership function area as output

### ISSUE THREAD

**Issue by mfigueredo** [scikit-fuzzy/scikit-fuzzy#157]
Hello,

I looked for some issue that could help me with this question, but i didn't find something similar. 
Is it possible get the area for each membership function after compute the results?

For example, in the Tipping [Problem](http://pythonhosted.org/scikit-fuzzy/auto_examples/plot_tipping_problem_newapi.html),  if i wish get the area or the membership for 'high', 'medium' and 'low' regions separately, this could be possible?

Thanks!

**Comment by JDWarner** [comment]
Assuming careful maintenance of units, you need simple trapezoidal integration.  NumPy has this built-in as the function `trapz`.  I'm not sure exactly what your use case is, though - fuzzy membership is functionally unitless.

For example, starting with the Tipping Problem, if you wanted to know the actual area (in units of universe_units * membership_units) you would simply run this after defining the Antecedent `tip`:

``` python
np.trapz(tip['low'].mf, tip['low'].parent.universe)
```

which, for me, yields 6.5.  

This isn't currently exposed in the package, and it's a little obtuse to get the necessary info.  If there is demand, it would be simple to expose it; feel free to lobby for this and/or educate me on how this is helpful to you!

Closing as resolved for now, but as stated, feel free to convince me to add this as a more direct method.

**Comment by mfigueredo** [comment]
I'm sorry but i guess my question was a little ambiguous. 

What i supposed to find is the area related(in Tipping Problem) to 'low', 'medium' and 'high' after the **compute inputs**. In this case, for 'low' should be 0.0(there is no blue filled area), for 'medium' the green area and the 'high' the red one. 

I'm looking for this solution because the Defuzzification  apparently calculated by centroid method is useless for me. What i want  to know is the my input relation with each output class.

Other solution would be not use the color area values, but the max value reached for each class. In the Tipping Problem, the 'low' wold be 0.0, the 'medium' 0.05(maybe) and the 'high' 0.98.

Is this possible?

**Comment by JDWarner** [comment]
@mfigueredo this is a more challenging thing to request than you might initially expect, because the entire framework is designed to be lean.  In other words, when the system is computed _only the Antecedent Terms connected to output Consequent Terms via Rules are actually computed_.

There really is no way around this, within the bounds of how the system is designed.  One could write a separate interpreter for a ControlSystemSimulation object that would attempt to exhaustively find and compute all Antecedent Term firings, likely borrowing some of the machinery from ControlSystemSimulation, but it would be outside the desired scope of the control systems module.

Now, if you are interested in the aggregate firing for each _Rule_ in the system, and by association the firing of their constituent Terms, that can be found.  Assuming your ControlSystemSimulation is named `controlsys`, call `controlsys.print_state()`, or interrogate the Rules in the ControlSystemSimulation by requesting their `rule.aggregate_firing[controlsys]`.

Does that make sense?  I'd also be interested in why the output values are useless for you.

**Comment by mfigueredo** [comment]
@JDWarner , let me first help you to understand my problem. Using a profile as input i'm trying relate one person with some kind of tourism. One example of output can be seen following:

![myout](https://user-images.githubusercontent.com/20688530/32421499-0bea8920-c278-11e7-8997-c765fd724305.png)

As you can see, the centroid is useless for me, because it doesn't mean anything in this situation. But i can say the input profile is strongly related to Historical tourism, followed by a Landscape. I need the relation between the profile and each class of tourism, what could be fount by the colored area or the max membership in each class.

Consider `tourist_classification` my _ControlSystemSimulation_ and `tourist` my _Consequent_. 
When i'm using `tourist.view(sim=tourist_classification)` to visualize the graph, somewhere in this blackbox are the values i would like to get have been used. Looking in the source i found this:

` crispy = CrispValueCalculator(self.fuzzy_var, sim) `
`ups_universe, output_mf, cut_mfs = crispy.find_memberships()` 

Aren't this values that i'm looking for?

**Comment by mfigueredo** [comment]
@JDWarner, first let me help you to understand my problem. I'm trying classify a profile containing _N_ features as a kind of costumer C1, C2 or C3. Passing my features as a dict my fuzzy output view should be similar in the Tipping Problem, but in my case there is not low, medium and high, but C1, C2 and C3. You should agree that centroid is really useless because doesn't mean anything. What i really would like to know is the profile relation between C1, C2 and C3 class.

![c1](https://user-images.githubusercontent.com/20688530/32422525-988f467a-c27f-11e7-9b9e-99838eb1aa0e.png)

Back to our problem, in Tipping example, the above image is generated using `tip.view(sim=tipping)`.
The answers from my problem shouldn't been in this method? Looking into the source i found the following code:

` crispy = CrispValueCalculator(self.fuzzy_var, sim)`
`ups_universe, output_mf, cut_mfs = crispy.find_memberships()`

My problem couldn't be solved using similar approach? How could be this applied to Tipping Problem?
I tried your last solution, but got a lot of error using it.

**Comment by JDWarner** [comment]
@mfigueredo sorry for dropping the ball on this, feel free to ping me in future if that happens again.  Thanks for explaining your problem.

This is again more challenging than it appears.  I'll try to shed some light on why.

When the system graph is created, Rules are the glue that connect everything together.  The graph can end up very (_very!_) complicated, but every Rule has defined inputs and outputs.

Because Rules are so central, the whole structure is built around them.  Including the computation engine that takes over when you call `.compute()`.  What I mean by this, is that the Terms each Rule is connected to are calculated... and then immediately aggregated into that Rule.  The results aren't actually cached, just the aggregates in the Rules.  This was done to make systems with intermediate cached results much leaner on memory.

As a result, you can't get individual Term firing from the Rules, nor from the Terms themselves.  At least, within the existing framework.

That said, you do have a very powerful NetworkX DiGraph available.  It's possible to do this.  But it would require an entirely separate approach to traversing the Graph with the goal to find and calculate all of the Terms.  That sounds like an interesting project, and all the tools are readily available - but it's outside the scope of scikit-fuzzy.

Let me know if you do pursue this.

**Comment by JordaoMemoria** [comment]
@mfigueredo
I found a good solution. I was having the same problem and a nice alternative is change the defuzzification method. The lib give us the five principle methods. Take a look.
<img width="169" alt="screen shot 2018-10-04 at 08 07 03" src="https://user-images.githubusercontent.com/6748394/46470302-871e1c80-c7ac-11e8-88c5-4ab9b090509c.png">
The defuzzification method is configured when the fuzzy variable is created. By default "centroid" is used by __init__ of "FuzzyVariable" and maybe, at least for me and you, "centroid" is not to good to approach the problem. So , what you have to do is change the defuzzification method on the creation of the CONSEQUENT fuzzy variable. Something like this:
<img width="803" alt="screen shot 2018-10-04 at 08 13 14" src="https://user-images.githubusercontent.com/6748394/46470545-63a7a180-c7ad-11e8-9683-49491ca2d145.png">

I know, is still not possible separate the consequent rules, but it helps a lot. It works for me and make me not give up of the lib.

Aqui também é Br HUE HUE
