### ISSUE TITLE
scikit-fuzzy 0.2.0 setup non-strict dependencies

### ISSUE THREAD

**Issue by rtatishvili** [scikit-fuzzy/scikit-fuzzy#158]
scikit 0.2.0 setup available on pip has non-strict dependencies that causes networkx==2.0 setup, which contains some breaking changes:

```
File ".../python3.6/site-packages/skfuzzy/control/controlsystem.py", line 126, in __setitem__
  matches = [n for n in self.sim.ctrl.graph.nodes()
File ".../python3.6/site-packages/networkx/classes/graph.py", line 717, in nodes
  nodes = NodeView(self)
File ".../python3.6/site-packages/networkx/classes/reportviews.py", line 168, in __init__
  self._nodes = graph._node
AttributeError: 'DiGraph' object has no attribute '_node'
```

The work-around is a manual roll-back of a networkx package to 1.9.0

`pip uninstall networkx`
`pip install networkx==1.9.0`

A solution would be making the dependencies strict.

Note: this applies to scikit-fuzzy 0.2.0, other versions I have not tested so far.

**Comment by JDWarner** [comment]
This is true; NetworkX introduced a number of breaking changes in 2.0.  Rather than limit to an old version of NetworkX, forward and reverse compatibility was introduced/fixed and is available in the 0.3 updated release of scikit-fuzzy.  

Updating your installation of this package should fix this and also bring significant performance and efficient improvements.
