### ISSUE TITLE
Using np.linspace instead of np.arange causes very different return values

### ISSUE THREAD

**Issue by Raphango** [scikit-fuzzy/scikit-fuzzy#165]
Hi!

I've just found out that using np.linspace instead of np.arange at the ctrl.Antecedent declaration causes very different return values.

Like the exampled tipping problem, if I use np.arange with 1 as step I get 19.847607362 as result:
`quality = ctrl.Antecedent(np.arange(0, 11, 1), 'quality')`
`service = ctrl.Antecedent(np.arange(0, 11, 1), 'service')`
`tip = ctrl.Consequent(np.arange(0, 26, 1), 'tip')
`

If I use np.arange with 0.01 as step I get 16.5871688747 as result:
`quality = ctrl.Antecedent(np.arange(0, 11, 0.01), 'quality')`
`service = ctrl.Antecedent(np.arange(0, 11, 0.01), 'service')`
`tip = ctrl.Consequent(np.arange(0, 26, 0.01), 'tip')`

But if I change to np.linspace, the result is 16.6451652297:
`quality = ctrl.Antecedent(np.linspace(0, 11, 100), 'quality')`
`service = ctrl.Antecedent(np.linspace(0, 11, 100), 'service')`
`tip = ctrl.Consequent(np.linspace(0, 26, 100), 'tip')
`

Using **1000** instead of **100** gives me 16.5616660943.

So, the difference is due to the step being discrete values instead of "continuous" value? Like, skfuzzy works normally with any length of numpy array?

**Comment by JDWarner** [comment]
Subtle.  Nothing is wrong with scikit-fuzzy; you're getting caught by certain subtle features of NumPy's `arange` and `linspace`.  Here's what is going on.  There are two important points:

1.  When `automf` is used, the membership functions span the available universe automatically.  
2.  The inputs chosen for the tipping problem - in particular, for `'service'` - are very close to the top of the desired range (9.8 out of 10).

The original code gives universes that span [0, 10] for _quality_ and _service_ - they terminate at 10, because `arange` is not inclusive on the high side.  Similarly, _tip_ terminates at 25, not 26.

Your alternatives change the intended universe ranges.  In the first example, they now span [0, **10.99**] and [0, **25.99**], respectively.  In the second alternative, they go all the way to [0, 11] and [0, 26].  This actually has a rather large effect on the result, because the correct result depends on _service_ being nearly maxed.

If you want to compare apples to apples, your first alternative would be 
``` python
quality = ctrl.Antecedent(np.arange(0, 10.01, 0.01), 'quality')
service = ctrl.Antecedent(np.arange(0, 10.01, 0.01), 'service')
tip = ctrl.Consequent(np.arange(0, 25.01, 0.01), 'tip')
```
which yields 19.8577592069.

The second alternative would be
``` python
quality = ctrl.Antecedent(np.linspace(0, 10, 100), 'quality')
service = ctrl.Antecedent(np.linspace(0, 10, 100), 'service')
tip = ctrl.Consequent(np.linspace(0, 25, 100), 'tip')
```
which yields 19.8571473785; these are within acceptable integration/precision error.

Scikit-Fuzzy is working properly.

**Comment by Raphango** [comment]
You are right. Thank you for your explanation. =)

By the way, how can I access the membership function values of variables that used automf? Like this:
`quality.automf(3)`

What I really would like to do is  access the tip membership function so I can change the defuzzifying method with the [defuzz()](http://pythonhosted.org/scikit-fuzzy/api/skfuzzy.html#defuzz) function.

Thanks again!

**Comment by JDWarner** [comment]
Membership functions (the actual NumPy arrays) are available as the `.mf` attribute of Term objects, i.e.,
``` python
quality['poor'].mf
```
or, equivalently without the shortcut (but less Pythonic, though this is what's actually going on),
``` python
quality.terms['poor'].mf
```

**Comment by Raphango** [comment]
Thank you!

**Comment by Raphango** [comment]
Just one more question: Is there any way to directly access the aggregated output membership function?
![2018-01-23 00_44_45-figure 1](https://user-images.githubusercontent.com/6752809/35255552-cb85c484-ffd6-11e7-9898-c118ce15a684.png)

In `tip.view(sim=tipping)` I can just view the plot, but I can't save the output membership function to a variable.

I have tried to use tip['low'].mf and so on but I just get the original membership function.

Thanks again!
