### ISSUE TITLE
Should universe values be sorted ? 

### ISSUE THREAD

**Issue by Imane0** [scikit-fuzzy/scikit-fuzzy#174]
Should `control.fuzzyvariable.FuzzyVariable` objects take as input a **sorted** universe list of values in an increasing order ?

**Comment by JDWarner** [comment]
Yes, the universe should be monotonic.

The reason this object does not do the sorting itself, is because the system allows interactive generation of objects and only the universe (not any membership functions) is provided at time the `FuzzyVariable` is instantiated.  If sorting happens at that time, it would be necessary at the very least to keep track of how that sorting was done (output from argsort) and then apply the sorting to every `Term`'s membership function when it gets added.  This would roughly double the memory required, and with an eye to embedded/minimal systems we have thus far resisted unnecessary memory burdens.  Furthermore, a big dangerous assumption here is that the user who provides an improper universe is going to maintain that exact same improper ordering through all of their fuzzy membership functions.

From a philosophical standpoint I am against the idea of a system which tries to smartly reorder provided data.  This type of magic provides problems.  People start thinking order doesn't matter, and then somewhere between when the `FuzzyVariable` is spawned and a `Term` gets added the order changes, because they thought magic was happening.  

What I would support, is a check at time of `FuzzyVariable` creation that the universe is monotonic; if not, an informative error would be returned.

**Comment by Imane0** [comment]
Thank you for the explanation! It should be mentioned somewhere in the docs that the input should be sorted. I haven't seen it, may be I missed it ?

**Comment by JDWarner** [comment]
It is rather a base assumption in the definition of a fuzzy universe.  'Sorting' a universe is dangerous, because you may lose meaning in your universe if associated values are not sorted exactly the same way.
