### ISSUE TITLE
Antecedent error

### ISSUE THREAD

**Issue by AmandaLBaker** [scikit-fuzzy/scikit-fuzzy#177]
I have just recently installed scikit-fuzzy, and when running the example.py to ensure things are running smoothly, I am given the error "AttributeError: 'module' object has no attribute 'Antecedent'" 

Is there a way to go about fixing this? I've tried multiple fuzzy packages to no avail, and would really like to get this one working. Running on a MacOSX and installed everything through the terminal, and am running the py files through the terminal, not an IDE.

**Comment by JDWarner** [comment]
Hmm, when you say you installed everything through the terminal, does that mean you are using the system Python, Homebrew, or the command line versions of something like Anaconda?

A full traceback of the error you are seeing would be helpful, because I don't recognize that error but it must be happening fairly early.

**Comment by trevery** [comment]
Hi, I meet this problem again.
env: macOS: 10.12.6 ; conda: 4.3.30; python: 3.6.2

I think we are facing the same problem. Firstly, I run `python example.py` after installing `numpy`,`scikit-fuzzy` with `conda`.  the interpreter told me I should add `()` because of python version changing. I fixed this problem. Then, I run the example again, this problem came out. Here is the full traceback:

```
Traceback (most recent call last):
  File "example.py", line 6, in <module>
    quality = fuzz.Antecedent(np.arange(0, 11, 1), 'quality')
AttributeError: module 'skfuzzy' has no attribute 'Antecedent'
```

**Comment by JDWarner** [comment]
You installed `scikit-fuzzy` with conda?

I wasn't aware there was a conda package for scikit-fuzzy.  The package may be old.  See what version you're using with 

``` python
import skfuzzy as fuzz
fuzz.__version__
```

If the result is under 0.3, the version is old.  I'd uninstall the conda version and reinstall with `pip`.

**Comment by trevery** [comment]
Hi JDWarner:

Here is my version.

```
>>> import skfuzzy as fuzz
>>> fuzz.__version__
'0.3.1'
```

**Comment by JDWarner** [comment]
Ah - I think I understand.  Where are you getting that particular `example.py`?  That's an old example.  The API has changed.

Previously, the Control objects were all exposed to the base namespace `fuzz.[Name]`.  This made discovering them non-ideal, because they were mixed with a lot of other basic fuzzy logic functions.

So it was changed that the control objects are now all exposed from `fuzz.control.[Name]` rather than `fuzz.[Name]`.  This way you can introspect the `fuzz.control` submodule and see everything which works together.

If that example file is still included with 0.3.1, it'll be updated and a new version tagged shortly (overdue for that in any event).

**Comment by sanaullahjan** [comment]
I am also having the same problem. Even after changing fuzz.[Name] to fuzz.control.[Name], I face the same problem. Any update about it?
![capture](https://user-images.githubusercontent.com/43025646/45143039-0ee82980-b1f5-11e8-96e6-85a6151c30d2.JPG)

**Comment by JDWarner** [comment]
This `example.py` dates to pre-0.2 and has incorrect, old syntax (the fuzzy control system classes were refactored exclusively into `skfuzzy.control` by the 0.2 release).

Please do not use `example.py`, see instead the [example gallery](https://pythonhosted.org/scikit-fuzzy/auto_examples/index.html).  The legacy `example.py` will be removed shortly, to avoid further confusion.

**Comment by KhaiCyber** [comment]
Hello 
I have a problem when i try to run file.py and i ran the file.py in Python 2.7. I also installed Scikit_Fuzzy was successful.  I presented some errors i met:
Traceback (most recent call last):
  File "/home/pi/Desktop/tip.py", line 2, in <module>
    import skfuzzy as fuzz
ModuleNotFoundError: No module named 'skfuzzy'

**Comment by scikit-fuzzy** [comment]
If you cannot import the base package, your package installation was not
successful - or it installed under a different python (virtual) environment
than you thought and are now running from.

**Comment by Fatsnake2** [comment]
it give a information "module 'skfuzzy' has no attribute 'Antecedent'" my python's version is 3.10, the version of scikit-fuzzy is 0.4.2
