### ISSUE TITLE
How to stop figures disappearing immediately when building in Sublime Text 3?

### ISSUE THREAD

**Issue by talfryn** [scikit-fuzzy/scikit-fuzzy#178]
.view() method opens and closes all the figures immediately. How to stop the figures from disappearing when building in Sublime Text 3.

**Comment by JDWarner** [comment]
This is by design; `.view()` returns the actual matplotlib Figure and Axis objects to allow the user to further edit or customize them as they desire.  It does not show the figure (unless you're using Jupyter, which is recommended).

To see the figure, use fig.show() or plt.show() after .view()

See also #125, #145.
