### ISSUE TITLE
Control Rule.view() from New API is not rendering any content

### ISSUE THREAD

**Issue by Oleksandr-Olefirenko** [scikit-fuzzy/scikit-fuzzy#180]
Dear Developers, 

I've digged into the lib, it's pretty amazing the way you've put the Pythonic way. 

However, the new example won't work for me. The plot is not rendering at all, I tried putting the app to sleep for a minute to check the graphs, but it never rendered.  Particularly the control.rule.view() method from the very example, by link below: 

https://pythonhosted.org/scikit-fuzzy/auto_examples/plot_tipping_problem_newapi.html

Please let me know how can I work-around it, as I wasn't able to find a proper answer at StackOverflow, ain't sure if you are monitoring the issues on the topic there.

I'm running Windows 10 x64 machine, using Python3.6, scikit-fuzzy lib v.0.3.1 with all the required libraries.

And strange thing is as an output for the suggested parameters I've got the value ~19.8687, not the article stated 20.2%, could you please clarify? 

Thank you!

**Comment by JDWarner** [comment]
Output is correct from the system, the example reflects an earlier pre-0.2 version which was before significant accuracy improvements were merged. 
 The example itself is fixed in master, will be pushed with next release (pending, been very busy).

You're not the first to ask about the figures.  The example generation framework automatically shows figures.  So does the Jupyter notebook (strongly recommended).  However, what the actual view command does is return the matplotlib figure and axis objects - so you can, if you desire, further customize the formatting for your purposes.  

When you want to see the figures, run plt.show()

**Comment by Oleksandr-Olefirenko** [comment]
Thank you, Josh, appreciate the help! Keep up the good work :)
