### ISSUE TITLE
Explanation of fuzzy rule graph

### ISSUE THREAD

**Issue by bbrighttaer** [scikit-fuzzy/scikit-fuzzy#181]
Please, is there any documentation explaining the fuzzy rule graph as a result of `rule.view()` such as found in [https://pythonhosted.org/scikit-fuzzy/auto_examples/plot_tipping_problem_newapi.html#example-plot-tipping-problem-newapi-py](url)? what do the nodes and edges represent?
Thanks.

**Comment by JDWarner** [comment]
It is a directed graph.  Nodes are Antecedents, Consequents, Terms, or Rules; the connections are made from the inputs to your Rules.  The entire flow is from input Antecedent Terms to output Consequent Terms, through the Rules.

I believe NetworkX has improved their plotting abilities since this was implemented; at the time adding labels made it almost impossible to read.  Ideally the graph would be laid out with more space, color coding for what each object is, and ideally with the above flow moving left to right.  This was simply not possible at the time, so there is certainly room for improvement!

**Comment by bbrighttaer** [comment]
thanks very much. any plans on when the possible updates could be released?
