### ISSUE TITLE
Updating control system configuration

### ISSUE THREAD

**Issue by enyucao** [scikit-fuzzy/scikit-fuzzy#194]
Hi,
I am working on a control system with dynamic membership setting. 

Is it possible to update the antecedent membership for one control system? I would like to initialize the control system once and update one  antecedent setting, rather than frequently creating/deleting the whole control system.

Here is an code segment 
```
init()
  ... #define antecedent/consequent
  global distance
  distance.automf(3) #just for initialization
  rule1... #rules
  fl_system=ctrl.ControlSystem(...)
  global system_instance
  system_instance = ctrl.ControlSystemSimulation(

callback()
  #dynamic custom membership functions ``
  **_horizon_size     #a variable 
  distance['poor'] =       fuzz.trimf(distance.universe, [0, 0, horizon_size])
  distance['average'] = fuzz.trimf(distance.universe, [0, horizon_size, horizon_size*2])
  distance['good'] =      fuzz.trimf(distance.universe, [horizon_size, horizon_size*2, horizon_size*2])_**
  #rules and other antecedents are not changed. 
  ...    #inputs
  system_instance.compute()
  result = system_instance.output['risk']
```

When I try to change membership functions after creating rules, I got the following error. Besides, could you tell me how to visualize the rule graph?
```
...
system_instance.compute()
  File "/usr/local/lib/python2.7/dist-packages/skfuzzy/control/controlsystem.py", line 336, in compute
    for rule in self.ctrl.rules:
  File "/usr/local/lib/python2.7/dist-packages/skfuzzy/control/controlsystem.py", line 704, in __iter__
    self._cache = list(self._process_rules(self.all_rules[:]))
  File "/usr/local/lib/python2.7/dist-packages/skfuzzy/control/controlsystem.py", line 753, in _process_rules
    raise RuntimeError("Unable to resolve rule execution order. "
RuntimeError: Unable to resolve rule execution order. The most likely reason is two or more rules that depend on each other.
Please check the rule graph for loops.
```

**Comment by JDWarner** [comment]
Partially yes, partially no.  The answer is why there are separate objects for the `ControlSystem` and `ControlSystemSimulation`.

You can make a control system object and dynamically do anything you want to it.  However, once you make a control system *simulation*, it needs to be static.  The reasons are related to the simulation changing during computation and the fact that prior runs are cached, which hugely increases performance for smaller systems.  These require confidence the system/rules framework is stable from prior runs, with different inputs the only significant difference.  This would not be simple to patch out.

So to do what you're looking for, you would need to pass the `ControlSystem` itself (potentially with the antecedent label so you can find the one you want) into later functions, change what you like, then make the ControlSystemSimulation.

**Comment by schadocalex** [comment]
I had the exact same "bug" of rule execution order without knowing this was due to dynamic configurations. I was looking for rules instead. It could be useful to detect this kind of error.
The workaround I use is to create a new instance of ControlSystem each time I want to modify parameters.

**Comment by EnyuCao** [comment]
Hi all,

Thank you for your reply. @JDWarner, I fully understand the difference between  `ControlSystem` and `ControlSystemSimulation` that you said. It will be great that the `ControlSystem` can be changed.

I wrote the following code to verify my idea. It is based on [the control system example](https://pythonhosted.org/scikit-fuzzy/auto_examples/plot_tipping_problem_newapi.html). The problem is the rules also seem static, and if I changed the membership function (e.g  quality.automf(7) ->  quality.automf(3)), the rules have to be assigned again. Please check my comments at Line 23 and Line 25.


    import numpy as np
    import skfuzzy as fuzz
    from skfuzzy import control as ctrl
    import random,time

    def init():

        quality = ctrl.Antecedent(np.arange(0, 11, 1), 'quality')
        service = ctrl.Antecedent(np.arange(0, 11, 1), 'service')
        tip = ctrl.Consequent(np.arange(0, 26, 1), 'tip')

        quality.automf(3)
        service.automf(3)

        tip['low'] = fuzz.trimf(tip.universe, [0, 0, 13])
        tip['medium'] = fuzz.trimf(tip.universe, [0, 13, 25])
        tip['high'] = fuzz.trimf(tip.universe, [13, 25, 25])

        rule1 = ctrl.Rule(quality['poor'] | service['poor'], tip['low'])
        rule2 = ctrl.Rule(service['average'], tip['medium'])
        rule3 = ctrl.Rule(service['good'] | quality['good'], tip['high'])
        
        #quality.automf(7) ##If I put new membership function here, I will get an error
        '''
        #I have to define the rules again
        '''
        global tipping_ctrl
        tipping_ctrl = ctrl.ControlSystem([rule1, rule2, rule3])

    def calc(quality,service):
        #I would like to change the control system( membership function) here, but how?
        tipping = ctrl.ControlSystemSimulation(tipping_ctrl)

        tipping.input['quality'] = quality
        tipping.input['service'] = service

        tipping.compute()

        print tipping.output['tip']

    if __name__ == '__main__':
        init()
        while True:
            quality = float(random.randint(0,11))
            service = float(random.randint(0,11))
            calc(quality,service)
            time.sleep(1)

If I uncomment the code in Line 23, the following error will show again. So it seems I have to declare the rules and control system again.

    ...
    system_instance.compute()
      File "/usr/local/lib/python2.7/dist-packages/skfuzzy/control/controlsystem.py", line 336, in compute
        for rule in self.ctrl.rules:
      File "/usr/local/lib/python2.7/dist-packages/skfuzzy/control/controlsystem.py", line 704, in __iter__
        self._cache = list(self._process_rules(self.all_rules[:]))
      File "/usr/local/lib/python2.7/dist-packages/skfuzzy/control/controlsystem.py", line 753, in _process_rules raise RuntimeError("Unable to resolve rule execution order. "
    RuntimeError: Unable to resolve rule execution order. The most likely reason is two or more rules that depend on each other.
    Please check the rule graph for loops.

Do you have some suggestion about properly change 'control system'?

**Comment by JDWarner** [comment]
@enyucao You are correct, it is not possible at present to delete or remove a rule in a `ControlSystem`.  This is because it gets *composed* into the underlying NetworkX system graph when it is added to the system.  This operation makes it very difficult to remove, as duplicate paths get combined for efficient computation.

So yes, you got me - you can do *almost* anything you like.  But at least at the moment, we don't have the ability to remove Rules - if you have a mis-defined Rule you will need to recreate the system.  Fortunately this is not a huge burden, with Jupyter notebooks etc. available.

The `Rule.antecedent` method is a setter.  They are not called as functions; you should think of a setter attribute like a variable.  In your last use case, this would have worked if you used the correct syntax 

`rule3.antecedent = quality['poor']`

Closing - though if someone really wanted the ability to delete Rule(s), this might be possible to add if the appropriate NetworkX feature(s) exist.
