### ISSUE TITLE
Output Membership Activity - The Tipping Problem - The Hard Way

### ISSUE THREAD

**Issue by K-Y-Saturn** [scikit-fuzzy/scikit-fuzzy#211]
We use minimum for if-then rule.  For example in

tip_activation_hi = np.fmin(active_rule3, tip_hi)

I think "Output Membership Activity" should be as the following (I got it from MATLAB and I used service=8.5 to have a better picture. The pic for value service=9.8 is hard to see).

![visualized rules](https://user-images.githubusercontent.com/46662902/51095532-ae549480-1772-11e9-989a-886775938a38.jpg)

The left and right sides of my blue trapezoid matches with the membership function (in your picture, in green, it does not).  Also, in the last rule, after 8.5 my graph gets completely flat (horizontal) but in you graph, in red, it has some slope.  

By the way, thanks for developing scikit-fuzzy. I like it alot!

**Comment by JDWarner** [comment]
First, thanks for using the package!  What you are seeing here happens when specifying a point which is not on the fuzzy universe as an input.  Correcting for this - which apparently MATLAB does - is not trivial even in a "let's do this the hard way" example.  Thus, the hard way example with defaults or your set of inputs will be a close approximation, but not quite exact.

If you want to fix this, in essence you have to inject a new universe points for every input that didn't exist before, rebuild the system with these in place, and re-run it.  

The good news is that **the `skfuzzy.control` Pythonic fuzzy control system builder absolutely does correct for this**, in an efficient and analytically correct manner.  Your membership universe can (and should!) be minimally sparse; only the points required to define the membership functions are necessary.  Everything else is filled in via linear interpolation and is exact for piecewise linear membership functions.

**Comment by JDWarner** [comment]
Closing as answered and fixed in `skfuzzy.control`, though I'm happy to elaborate further if you like.
