### ISSUE TITLE
why do we need to send the dataset in skfuzzy membership function definition?

### ISSUE THREAD

**Issue by majumderS** [scikit-fuzzy/scikit-fuzzy#222]
I am implementing a FLC and I need to implement a gaussian membership function for the same. 
1) I am not getting a smooth membership function. what could be the reason?
 2) also why do we need to send dataset to gaussmf function, when membership functions are drawn intuitively based on expert knowledge and also I am sending parameters for drawing the same. 
![fuzz1](https://user-images.githubusercontent.com/8430165/62125186-0f485200-b2ea-11e9-86e9-c7ad35972ab1.JPG)

**Comment by JDWarner** [comment]
Everything is based on an underlying sparse universe, as defined in the fuzzy logic literature which simplifies and reduces memory expenditure.  Your Gaussian function is thus rendered, if you will, only at the resolution defined by the fuzzy universe (which can be piecewise defined but most be monotonic).  Any values between defined values are interpolated by linear interpolation at computation time.

If you want a smoother representation, you can increase the resolution of your universe.  But before you do this, please consider if it's actually going to make a difference in the control space.  Test this, because the vast majority of the time you just increased computation time with no benefit.

**Comment by JDWarner** [comment]
In summary this is working as intended.

**Comment by majumderS** [comment]
Thank you.
