### ISSUE TITLE
Remove ordereddict.py ?

### ISSUE THREAD

**Issue by kinow** [scikit-fuzzy/scikit-fuzzy#240]
Hi,

The project Setuptools configuration does not use a [python_requires](https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires), but the classifiers are using `'Programming Language :: Python :: 3',`, and I think it is using Python3 valid-code.

If that's correct, then `skfuzzy.control.ordereddict` can be deleted I guess?

**Comment by JDWarner** [comment]
There are several places where the 2.6 compatible import is still used - it tries to import from `collections` and if it fails, gets it internally.

It would be reasonable to remove this and the compatible imports now, as well as the tests for the ordered dict monkey patch.  It's been some time since 2.6 was removed from the test suite and isn't officially supported, and I believe 2.7 had ordered dicts.

The Python world has been moving more aggressively toward requiring 3.x, but given fuzzy systems may be run on older or less capable systems, I'd like to keep 2.7 around until there's a compelling reason to drop it.

**Comment by kinow** [comment]
Sounds reasonable 👍
