### ISSUE TITLE
Problem with error : "super(type, obj): obj must be an instance or subtype of type"

### ISSUE THREAD

**Issue by Sebastien-8** [scikit-fuzzy/scikit-fuzzy#249]
Hello,

I try to run the example "Fuzzy Control Systems: Advanced Example" .
But
if I have installed scikit-fuzzy with **pip install** (what ever the version) i have the following error :
_super(type, obj): obj must be an instance or subtype of type_ 
at _error = ctrl.Antecedent(universe, 'error')_

if I have installed scikit-fuzzy with **conda forge** (what ever the version) i have the following error : 
_generator raised StopIteration_
at _system = ctrl.ControlSystem(rules=[rule0, rule1, rule2, rule3, rule4])_

The example and my own code used to work before i change my computer
I have the same problem on 2 different computers

Setting : 
Windows 10
Spyder 4.0.1

I don't have any clues of what i can do to fix this problem
Thank you in advance for your help

**Comment by JDWarner** [comment]
Need more information.  Specifically exactly which version of Python you're running, because Spyder uses an internal version of Python, I am unsure which version but probably 3.7.x - however you can set its interpreter to use others you may have also installed.  You can have all sorts of Python versions as Conda virtual environments.

Please always post full tracebacks.

The first error I've never seen before and need more information.  The second error should be fixed in #212, which was fixed and pushed to pip and conda-forge as of scikit-fuzzy 0.4.1.  I just double checked and conda-forge now has 0.4.2, and it definitely passes their build matrix on 3.7.x.  My best guess on the second is you for some reason are forcing conda to install a version of scikit-fuzzy older than 0.4.1.

**Comment by Sebastien-8** [comment]
First of all, thank you for your answer and sorry for the missing information

About the problems  :

For the second error [SOLVED]  : **generator raised StopIteration** , i saw the #212 this is why a updated my version of scikit-fuzzy and  i got the new error. In fact I have Python 3.7.3 and a run the -c conda-forge/label/gcc7 scikit-fuzzy__ and get scikit-fuzzy==0.3.1 . I think it was a mistake because now i get scikit-fuzzy==0.4.2 with -c conda-forge/label/cf202003 scikit-fuzz

For the first error : **super(type, obj): obj must be an instance or subtype of type** 
Actually the error occurs when i upgraded or downgrade scikit-fuzzy  and i did not restart the Kernel

Do not hesite if you need more information and sorry for lake of knowledges

**Comment by JDWarner** [comment]
Yes, if you change the version of any Python package and do not restart your kernel it will create problems.  Please use the most up to date version of scikit-fuzzy.

I believe these issues are resolved; feel free to reopen if they are not.
