### ISSUE TITLE
Sparse fuzzy rules, how it works?

### ISSUE THREAD

**Issue by Yuyang01** [scikit-fuzzy/scikit-fuzzy#250]
Hello, 

I am new in this area and thanks for providing this great tool. 

I don't understand how the scikit-fuzzy works when it is sparse fuzzy rules? Doest it need special algorithm?

Best,
Yuyang

**Comment by JDWarner** [comment]
Many traditional curricula taught the fuzzy universe variable should be continuously sampled.  If your range was 0-10, it should be densely populated [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10].  But if your desired fuzzy membership functions needed to have critical values somewhere between - say at 7.5 - most people increased the sampling of the whole universe and all membership functions.

This is unnecessary in scikit-fuzzy.

Include in the universe only the critical points where your membership functions must be defined.  If that's three triangular membership functions with endpoints at 0, pi, and 10, your universe need only include those three elements (in order).  It is sparse.  Everything else is interpolated with perfect accuracy as long as you include the critical values.

Most people are using triangular or otherwise piecewise membership functions where this reaps huge gains.  If your membership functions for some reason must be continuous (sigmoid, etc) then you'll need some form of continuous sampling.

**Comment by Yuyang01** [comment]
Dear @JDWarner 
Thank you for writing me great explanation. I might propose an example to ask. Let us consider a fuzzy rule based system where two input variables (x1 and x2) and a single output variable (y) are involved, with the following terms sets associated: {small, medium, large}, {short, medium, long} and {bad, medium, good}, respectively. I have the only three rules:

1. If X1 is small and X2 is short, then Y is bad
2. If X1 is large and X2 is large, then Y is good. 
3. If X1 is medium, then Y is medium

**Is it enough to solve the problem with only three rules?**
 It seems I need to have **at least** 3*3=9 rules?  I don't understand how many rules is enough for a problem, and that's why I asked how to solve the spare rule.

**Comment by JDWarner** [comment]
This is not the forum for practical advice/consultation on fuzzy system design.

Functionally you need enough rules such that for every possible combination of inputs you will have a nonzero area under the combined response function when the system output is calculated.  Put differently, if any point on any universe can result in a uniformly zero response from all membership functions connected to all Rules in the system, it is too sparse.

**Comment by Yuyang01** [comment]
As I didn't find appropriate forum, I think you are expert in this area. 
Thank you for the constructive  answers.:)
