### ISSUE TITLE
Bug and its possible solution (with drawing graph in Jupyter)

### ISSUE THREAD

**Issue by pmelikov** [scikit-fuzzy/scikit-fuzzy#286]
Hello!

I am using JupytherLab 3.2.1, Python 3.8.2 and latest versions of all libraries.

I am studying this notebook: https://scikit-fuzzy.github.io/scikit-fuzzy/auto_examples/plot_tipping_problem_newapi.html#example-plot-tipping-problem-newapi-py.

When `quality['average'].view()` is executed, the graph is displayed, but Warning is displayed before the graph (see screenshot):

```
...\scikit-fuzzy-master\scikit-fuzzy-master\skfuzzy\control\term.py:72: UserWarning: Matplotlib is currently using module://matplotlib_inline.backend_inline, which is a non-GUI backend, so cannot show the figure.
  fig.show().
```
![image](https://user-images.githubusercontent.com/37336797/151957128-1519fb17-201d-480f-9d7c-71bfe3f95558.png)

If in the files `...\scikit-fuzzy-master\scikit-fuzzy-master\skfuzzy\control\term.py` and `....\scikit-fuzzy-master\scikit-fuzzy-master\skfuzzy\control \fuzzyvariable.py` replace the `view()` method code as follows, then no Warning will occur when this notebook is executed and the graphs will be displayed as expected.

```python
    def view(self, *args, **kwargs):
        """""" + FuzzyVariableVisualizer.view.__doc__
        #fig, ax = FuzzyVariableVisualizer(self).view(*args, **kwargs)
        #fig.show()
        FuzzyVariableVisualizer(self).view(*args, **kwargs)
```

If replace `%matplotlib inline` with `%matplotlib qt`, then there are no Warning either.

But if you replace `%matplotlib inline` with `%matplotlib widget`, then there are no Warnings, but two identical plots are displayed! It is not good.

![image](https://user-images.githubusercontent.com/37336797/151958122-2e6baada-e628-4711-9509-c1ad15c23a86.png)

Please check the indicated place in the code and consider my solution. It is possible that the method I have indicated is normal.

I want to ask you to also update the version of laptops, because when you first start the laptop, the following message is displayed:

```
Notebook converted
This notebook has been converted from an older notebook format (v3) to the current notebook format (v4). The next time you save this notebook, the current notebook format (v4) will be used. 'Older versions of Jupyter may not be able to read the new format.' To preserve the original format version, close the notebook without saving it.
```

**Comment by JDWarner** [comment]
Thank you for the report.  I verified these notebooks still work as expected when running on a local Jupyterlab server. That is what I imagine the majority of users will be doing.  From some of the GUI overlays in the clips you show, I suspect you are running them in Google CoLab or a similar cloud host.

It's very difficult to make one set of code motifs which works everywhere, especially in an evolving landscape of cloud hosted notebooks.  You are correct that these throw warnings in some backends, but removing the `.show()` lines in the `.view()` methods makes them *not work at all in non-GUI or non-Jupyter environments* (the figure is built but not shown, no window is spawned).  This is much more frustrating for those users than having some people see a warning alongside working code - note you are getting the correct figure displayed.  The goal of the code is to *work* across as many diverse Matplotlib backends and environments as possible.  To that end, I do not think removing `.show()` is wise.

The notebooks are auto-generated by Sphinx and use the lowest forward-compatible version of Jupyter by design. They are converted transparently when opened in newer versions.  This simply retains backwards compatibility for anyone who happens to be running or stuck on an old version of Jupyter.  When/if there are substantive updates the notebooks may be updated.

**Comment by pmelikov** [comment]
I use the latest jupytherlab and other packages versions for now. Not cloud or any alternatives. So desired problem is real.
Ok, never mind.
Thanks for answer.
Whoever has to solve this problem can find it description here.
