### ISSUE TITLE
AttributeError: 'module' object has no attribute 'Antecedent'

### ISSUE THREAD

**Issue by brunobro** [scikit-fuzzy/scikit-fuzzy#90]
When execute the script /docs/examples/plot_tipping_problem_newapi.py, appear the error message:

Traceback (most recent call last):
  File "./PESQUISAS/AGRICULTURA/scripts/fuzzy.py", line 52, in <module>
    quality = fuzz.Antecedent(np.arange(0, 11, 1), 'quality')
AttributeError: 'module' object has no attribute 'Antecedent'

**Comment by JDWarner** [comment]
This is expected. The new API is still under active development and is not yet released; it will be available in version 0.2.x. 

If you want to use these features immediately you should clone this repository and install using `python setup.py develop` instead of using pip, at least until 0.2 is out.
